language: node_js
node_js:
    - "4.1"
before_install:
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update
    - sudo apt-get install -y gdal-bin python-gdal imagemagick
before_script:
    - mkdir -p test/data
    - pushd test/data
    - sh setup_data.sh
    - popd
script:
    - npm test
notifications:
    email: false
